---
- name: Create bin dir
  file:
    state: directory
    path: "{{ workspace }}/bin/"

- name: Get openshift clients
  get_url:
    url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift.install_version }}/openshift-client-linux-{{ openshift.install_version }}.tar.gz"
    dest: "/tmp/oc.tar.gz"

- name: Extract Openshift clients
  unarchive:
    src: "/tmp/oc.tar.gz"
    dest: "{{ workspace }}/bin/"
    remote_src: yes
    include:
      - oc
    selevel: s0
    serole: object_r
    setype: bin_t
    seuser: system_u
    mode: 0755

- name: Get release info
  command: "{{ workspace }}/bin/oc adm release info {{ openshift.install_version }} -o json"
  register: info

- set_fact:
    release_image: "{{ (info.stdout | from_json).image }}"  

- name: Extract bare metal installer
  command: "{{ workspace }}/bin/oc adm release extract --command=openshift-baremetal-install --to={{ workspace }}/bin {{ release_image }}"

- name: Symlink kubectl
  file:
    state: link
    src: "{{ workspace }}/bin/oc"
    dest: "{{ workspace }}/bin/kubectl"
      
