openshift:
  name: test6
  install_version: 4.9.13
  coreos_version:  4.9.0
key:
  pullsecret: "{{ lookup('file', '../pull-secret.json') }}"
  sshkey: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
# OpenShift Network
net:
  domain: ipv6.virtual.cluster.lab
  cluster_cidr: fc01::/48
  cluster_prefx: 64
  service: fd02::/112
# libvirt net
libvirt:
  name: openshiftv6
  cidr: fd12:dead:beef:2::/64
  bridge: openshift0
registry:
  user: openshift
  password: openshift
