ansible_host: "{{ libvirt.cidr | ansible.netcommon.nthhost(4 + groups['control'].index(inventory_hostname)) }}"
spec:
  cpu: 4
  ram: 16384
  disk: 128
  disk_cache: unsafe
  mac: "{{ '52:54:00' | community.general.random_mac(seed=inventory_hostname) }}"
